apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: game-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wow-acc
  namespace: game-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wow-ClusterRole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wow-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wow-ClusterRole
subjects:
  - kind: ServiceAccount
    name: wow-acc
    namespace: game-operator

---
apiVersion: v1
kind: Pod
metadata:
  name: game-operator
  namespace: game-operator
spec:
  containers:
  - name: game-operator
    image: hellof20/wow-operator:v2
    imagePullPolicy: Always
  serviceAccountName: wow-acc
