apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: realms.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: realms
    singular: realm
    kind: Realm
    shortNames:
    - realm
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string                
              image:
                type: string
          status:
            type: object
            properties:
              ready:
                type: string
              external_ip:
                type: string                
    subresources:
      status: {}                
    additionalPrinterColumns:
    - name: ID
      type: string
      jsonPath: .spec.id
    - name: NAME
      type: string
      jsonPath: .spec.name
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    - name: Ready
      type: string
      jsonPath: .status.ready
    - name: EXTERNAL_IP
      type: string
      jsonPath: .status.external_ip         