---
apiVersion: v1
kind: Pod
metadata:
  name: wow-operator
spec:
  containers:
  - name: wow-operator
    image: asia.gcr.io/gcp-wow/wow-operator:v1
    imagePullPolicy: Always
    env:
      - name: host
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: host
      - name: user
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: user
      - name: password
        valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: password               
  serviceAccountName: wow-acc