apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: realm-${realm_id}
  name: realm-${realm_id}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realm-${realm_id}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: realm-${realm_id}
        game: wow
    spec:
      containers:
      - image: ${realm_image}
        imagePullPolicy: Always
        name: realm
        command: ["worldserver"]
        ports:
        - containerPort: 8085
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5        
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "2048Mi"
            cpu: "2"
        volumeMounts:
        - name: config
          mountPath: /etc/worldserver.conf
          subPath: ${namespace}-realm-${realm_id}.conf
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: realm-${realm_id}-configmap
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: realm-${realm_id}
  name: realm-${realm_id}
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: realm-${realm_id}
  type: LoadBalancer
