apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sdk
  name: sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sdk
    spec:
      containers:
      - image: hellof20/trinitycore-regisiter
        name: trinitycore-regisiter
        command: ["python","sdk.py"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sdk
  name: sdk
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sdk
  type: LoadBalancer
status:
  loadBalancer: {}
