apiVersion: "stable.example.com/v1"
kind: WOW
metadata:
  name: pwm-wow
  finalizers:
  - stable.example.com/finalizer  
spec:
  sdk_port: 80
  sdk_image: hellof20/wow-sdk:v1
  sdk_replicas: 1
  auth_image: hellof20/auth
  realm_id: 3
  realm_image: hellof20/realm
  realm_name: 麦迪文
  create_mysql: "no"
  mysql_host: your_mysql_ip_address
  mysql_user: your_mysql_user
  mysql_password: your_mysql_password